import sys
from cx_Freeze import setup, Executable
build_exe_options = {
"includes": ["pyproj.datadir","tqdm"],
"excludes": ["tkinter",
"PyQt5",
"pygments",
"scipy",
"_bz2",
"_decimal",
"_hashlib",
"_lzma",
"_socket",
"select",
"unicodedata",
'asyncio',
 'attr',
 'backcall',
 'backports',
 'bs4',
 'certifi',
 'cffi',
 'chardet',
  'collections.abc',
 'colorama',
 'cryptography',
 'cssselect',
 'ctypes',
 'curses',
 'Cython',
 'dateutil',
 'defusedxml',
 'docutils',
 'email',
 'et_xmlfile',
 'html',
 'http',
 'idna',
 'importlib.abc',
 'importlib_metadata',
 'ipykernel',
 'ipyparallel',
 'IPython',
 'ipython_genutils',
 'jedi',
 'jinja2',
 'joblib',
 'jsonschema',
 'jupyter_client',
 'jupyter_core',
 'lib2to3',
 'llvmlite',
 'lxml',
 'markupsafe',
 'matplotlib',
 'msilib',
 'multiprocessing',
 'nbconvert',
 'nbformat',
 'nose',
 'notebook',
 'numba',
 'numpy',
 'openpyxl',
 'pandas',
 'parso',
 'pkg_resources',
 'prompt_toolkit',
 'pycparser',
 'pydoc_data',
 'pyrsistent',
 'pytz',
 'pyximport',
 'qtpy',
 'requests',
 'setuptools',
 'simplejson',
 'soupsieve',
 'sphinx',
 'sqlalchemy',
 'sqlite3',
 'testpath',
 'tornado',
 'traitlets',
 'unittest',
 'uritemplate',
 'urllib3',
 'wcwidth',
 'win32com',
 'xlrd',
 'xml',
 'xmlrpc',
 'yaml',
 'zmq',
 '_distutils_hack'], "optimize": 2, "include_files": ['.convert/']}

base = None

setup(
    name = "Chop Tiles",
    version = "0.1",
    options = {"build_exe": build_exe_options},
    executables = [Executable("chopTiles.py", base=base)]
)
